apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-service-logger1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-service-logger1
  template:
    metadata:
      labels:
        app: node-service-logger1
    spec:
      containers:
      - name: node-service-logger1
        image: vamsipothireddy/node-service-logger1:latest  # Updated image reference from Docker Hub
        ports:
        - containerPort: 3000
