apiVersion: v1
kind: Service
metadata:
  name: node-service-logger1-service-nodeport-mode
spec:
  type: NodePort
  selector:
    app: node-service-logger1
  ports:
  - port: 80 # port on cluster , Node is minikube and inside minikube we will have cluster
    targetPort: 3000 # this port should be same is conatiner port
    nodePort: 30007  # this is port on node , ie ip address of minikube
  