apiVersion: v1
kind: Service
metadata:
  name: rest-nodejs-app-service
spec:
  selector:
    app: rest-nodejs-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
