---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-service-logger1
  namespace: game-2048  # Explicitly set the namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-service-logger1
  template:
    metadata:
      labels:
        app: node-service-logger1
    spec:
      containers:
      - name: node-service-logger1
        image: vamsipothireddy/node-service-logger1:latest  # Updated image reference from Docker Hub
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: node-service-logger1-service
  namespace: game-2048  # Explicitly set the namespace
spec:
  selector:
    app: node-service-logger1
  ports:
  - port: 80 # port on cluster
    targetPort: 3000 # this port should be same as container port
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-node-service-logger1
  namespace: game-2048  # Explicitly set the namespace
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    #alb.ingress.kubernetes.io/group.name: "shared-alb"  # Same group name to share ALB
    alb.ingress.kubernetes.io/healthcheck-path: /log/sample1  # Set the health check path
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
        - path: /log
          pathType: Prefix
          backend:
            service:
              name: node-service-logger1-service
              port:
                number: 80  # Make sure the service port is 80 as defined above
