apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-service-logger1-with-volumemount
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-service-logger1
  template:
    metadata:
      labels:
        app: node-service-logger1
    spec:
      containers:
      - name: node-service-logger1
        image: vamsipothireddy/node-service-logger1:latest
        ports:
        - containerPort: 3000
        
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
          readOnly: true
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
      volumes:
      - name: config-volume
        configMap:
          name: db-configmap
